### ISSUE TITLE
Please fix

### ISSUE THREAD

**Issue by mkalioby** [Sirneij/django_mfa2_example#1]
Hello, 

https://github.com/Sirneij/django_mfa2_example/blob/70555e580c9bff794265999f41dee54dcd05ab5b/accounts/views.py#L28

This line shall be
 ```python
redirect(reverse('fido2_begin_reg'))
```

**Comment by Sirneij** [comment]
Ouch, fixed!

**Comment by mkalioby** [comment]
So how is it now?

**Comment by Sirneij** [comment]
It is still downloading `begin_reg`.

**Comment by mkalioby** [comment]
Downloading what? please send a screenshot

**Comment by Sirneij** [comment]
> Downloading what? please send a screenshot


![Screenshot from 2021-05-24 11-29-46](https://user-images.githubusercontent.com/29700390/119335104-cf531b80-bc83-11eb-9686-aaae355d8f09.png)

This is what I keep getting.

**Comment by mkalioby** [comment]
Can you give me write privilege to the repo to push updates?

**Comment by mkalioby** [comment]
Registration is Done, please note that you need https for webauthn to work.
Next is for you to fix login.
